draw_set_font(fntDefault)
draw_set_valign(fa_center)
draw_set_halign(fa_center)
draw_sprite_stretched(sNineSliceSprite, index, xPos, yPos, btnWidth, btnHeight)
draw_set_color(c_white)
draw_text(xButtonPos, yButtonPos, text)